### ISSUE TITLE
[Podification] Create Operator for Lifecycle Management

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#355]
The expectation here is for a single operator that will pretty much handle what the deploy script does today.

I would expect the following parameters to continue to be configurable from the CR with the current default values to still be the defaults if not provided in the CR:
```
APP_NAME
APPLICATION_ADMIN_PASSWORD
APPLICATION_DOMAIN
DATABASE_HOSTNAME
DATABASE_NAME
DATABASE_PORT
DATABASE_USER
DATABASE_PASSWORD
DATABASE_REGION
DATABASE_VOLUME_CAPACITY
ENCRYPTION_KEY
GUID
HTTPD_CPU_REQ
HTTPD_IMAGE_NAME
HTTPD_IMAGE_TAG
HTTPD_MEM_LIMIT
HTTPD_MEM_REQ
IMAGE_PULL_SECRET
MEMCACHED_CPU_REQ
MEMCACHED_IMAGE_NAME
MEMCACHED_IMAGE_TAG
MEMCACHED_MEM_LIMIT
MEMCACHED_MEM_REQ
ORCHESTRATOR_CPU_REQ
ORCHESTRATOR_IMAGE_NAME
ORCHESTRATOR_IMAGE_NAMESPACE
ORCHESTRATOR_IMAGE_TAG
ORCHESTRATOR_MEM_LIMIT
ORCHESTRATOR_MEM_REQ
POSTGRESQL_CPU_REQ
POSTGRESQL_IMG_NAME
POSTGRESQL_IMG_TAG
POSTGRESQL_MAX_CONNECTIONS
POSTGRESQL_MEM_LIMIT
POSTGRESQL_MEM_REQ
```

The operator should handle deploying, upgrading, and removing installations of manageiq by deploying the base dependencies (memcached, httpd, postgresql) and the orchestrator. It should not handle any use of manageiq such as adding or removing providers or changing settings.

---

- [x] Initial operator creation: [PR](https://github.com/ManageIQ/manageiq-pods/pull/389)
- [x] Build in the Dockerfile directly: [Issue](https://github.com/ManageIQ/manageiq-pods/issues/403) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397314395)
- [x] Add gofmt to CI: [PR](https://github.com/ManageIQ/manageiq-pods/pull/395) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-602876631)
- [x] Add build to CI - [Issue](https://github.com/ManageIQ/manageiq-pods/issues/404) [PR](https://github.com/ManageIQ/manageiq-pods/pull/412)
- [x] Set up CI to at least verify build ~~and gofmt~~: gofmt [PR](https://github.com/ManageIQ/manageiq-pods/pull/395) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-602876631)
- [x] Switch to go modules: [PR](https://github.com/ManageIQ/manageiq-pods/pull/400) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-603300089)
- [x] Update to latest boilerplate for operator-sdk: [Issue](https://github.com/ManageIQ/manageiq-pods/issues/405) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-603447748) in [PR](https://github.com/ManageIQ/manageiq-pods/pull/432)
- [x] Change "kind" from "Manageiq" to "ManageIQ": [Issue](https://github.com/ManageIQ/manageiq-pods/issues/406) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397324661) in [PR](https://github.com/ManageIQ/manageiq-pods/pull/444)
- [x] Change the boilerplate roles to something more restrictive: [Issue](https://github.com/ManageIQ/manageiq-pods/issues/407) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397319716) in [PR](https://github.com/ManageIQ/manageiq-pods/pull/413)
- [x] Fully spelled out keys: [Issue](https://github.com/ManageIQ/manageiq-pods/issues/408) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397322227) in [PR](https://github.com/ManageIQ/manageiq-pods/pull/416)
- [x] Certs available outside of the build: [Issue](https://github.com/ManageIQ/manageiq-pods/issues/409) originally discussed [here](https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397344335) in [PR1](https://github.com/ManageIQ/manageiq-pods/pull/431) and [PR2](https://github.com/ManageIQ/manageiq-pods/pull/445)
- [x] Do we need productizable kind names based on APP_NAME ?  Not even sure that's possible. [Issue](https://github.com/ManageIQ/manageiq-pods/issues/410)
- [x] Some other minor formatting cleanup and variable naming

**Comment by ChainZeeLi** [comment]
I'm working on implementing the operator in Golang, but realized the overwhelming amount of cr instances needing to be translated from yaml into golang objects. I choose Golang because of programmability and ease for future maintainance. Would you pick golang or ansible?

**Comment by carbonin** [comment]
@Fryguy We mentioned this briefly, but I feel like golang is probably better for the type of conditional logic we may need during an upgrade. Unfortunately we don't have a whole lot of golang expertise to do the review. @Fryguy what do you think?

**Comment by Fryguy** [comment]
I am good with any language really...either Go or Ansible would work for me.

**Comment by Fryguy** [comment]
I am good with any language really...either Go or Ansible would work for me.

**Comment by ChainZeeLi** [comment]
i decided to go with golang after discussion with Fabien. How do you want to name the operator and cr? Considering the operator code may be leveraged for manageiq upstream, maybe it's for the best to get synced on some namings.

**Comment by carbonin** [comment]
So we just recently went through a bit of work to get the app name configurable in https://github.com/ManageIQ/manageiq-pods/pull/369.

If we can do something similar (or at least leave the option open) that would be best. Otherwise I think "manageiq" for the CR kind. Since we will only have one CRD can the operator also be "manageiq" or is there a different naming convention for the operator itself?

**Comment by ChainZeeLi** [comment]
CRD and new k8s apis get created before the operator so the name has to be predetermined. For the operator itself, you can use any name but typically with suffix  "-opeartor"

**Comment by ChainZeeLi** [comment]
> So we just recently went through a bit of work to get the app name configurable in #369.
> 
> If we can do something similar (or at least leave the option open) that would be best. Otherwise I think "manageiq" for the CR kind. Since we will only have one CRD can the operator also be "manageiq" or is there a different naming convention for the operator itself?

CRD and new k8s apis get created before the operator so the name has to be predetermined. For the operator itself, you can use any name but typically with suffix "-opeartor"

**Comment by fdupont-redhat** [comment]
Shouldn't the operator live in it own repo?

**Comment by carbonin** [comment]
> CRD and new k8s apis get created before the operator so the name has to be predetermined

These could still be templated though, right? The actual CRD yaml could be in a template.

**Comment by carbonin** [comment]
@fdupont-redhat I'm not sure. That's more of a question for @Fryguy.

We debated breaking out each of the images into a separate repo, but since they're so interdependent we figured it made sense for them all to live here.

For testing and such it might make sense for the actual operator code to live in it's own repo, but I figure the dockerfile could still live here. I'm up for suggestions on this though.

Additionally I would think we would re-use the template files in some way so we don't have two sources of truth for how to deploy the application (not sure if the operator will be the only choice). So it would likely be easier for the container image to live here if it was going to include the templates.

**Comment by ChainZeeLi** [comment]
> > CRD and new k8s apis get created before the operator so the name has to be predetermined
> 
> These could still be templated though, right? The actual CRD yaml could be in a template.

Yes, the operator 

> @fdupont-redhat I'm not sure. That's more of a question for @Fryguy.
> 
> We debated breaking out each of the images into a separate repo, but since they're so interdependent we figured it made sense for them all to live here.
> 
> For testing and such it might make sense for the actual operator code to live in it's own repo, but I figure the dockerfile could still live here. I'm up for suggestions on this though.
> 
> Additionally I would think we would re-use the template files in some way so we don't have two sources of truth for how to deploy the application (not sure if the operator will be the only choice). So it would likely be easier for the container image to live here if it was going to include the templates.

If we use golang, there is no way to create resources using the templates. Ansible supports resource creation with yaml, but it's hard to implement complex logic with it.

**Comment by carbonin** [comment]
Presumably golang can parse yaml.

I know it's not an ideal architecture, but I really don't think it's a good idea to have two parallel implementations of the deployment information.

**Comment by ChainZeeLi** [comment]
> Presumably golang can parse yaml.
> 
> I know it's not an ideal architecture, but I really don't think it's a good idea to have two parallel implementations of the deployment information.

I thought about building a template parser too. There is a library for parsing yaml, but still need to design a clean way to map the values to golang object fields.

**Comment by carbonin** [comment]
@ChainZeeLi I think all of the openshift tooling is go. Maybe whatever is implementing the templating in `oc` or the openshift API is reusable?

**Comment by ChainZeeLi** [comment]
> @ChainZeeLi I think all of the openshift tooling is go. Maybe whatever is implementing the templating in `oc` or the openshift API is reusable?

Just realized that you can do yaml.unmarshall("*.yaml") to parse yaml files into golang structs. golang offers good support for this kind of parsing :) I can proceed with this method if you think it's clean enough.

**Comment by carbonin** [comment]
I think I would prefer it as a first pass at least.

I would say we can move over to a more typical operator arch when we are sure we are okay with the operator as the main/only install method and the manageiq community/core team is comfortable maintaining it.

**Comment by Fryguy** [comment]
@ChainZeeLi any updates?  I remember we saw the code last week and I think you were going to make a PR with it?

**Comment by mali-chainzee** [comment]
> @ChainZeeLi any updates? I remember we saw the code last week and I think you were going to make a PR with it?

Made some updates to the code earlier this week. Do you want me to make PR to this repo or should we use a seperate repo?

**Comment by Fryguy** [comment]
This repo please.

**Comment by mali-chainzee** [comment]
> This repo please.

just made the PR. Fabien and I talked about using a cr to represent restore/backup operation. guess we can just make another controller for this?

**Comment by Fryguy** [comment]
Let's do backup/restore as a separate PR entirely so as not to do too much at once

**Comment by Fryguy** [comment]
Follow up items to complete:

- [ ] Build in the Dockerfile directly: https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397314395
- [ ] Set up CI to at least verify build and gofmt: https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-602876631
- [ ] Switch to go mod: https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-603300089
- [ ] Perhaps update to latest boilerplate for operator-sdk 0.16: https://github.com/ManageIQ/manageiq-pods/pull/389#issuecomment-603447748
- [ ] Determine if "kind" can be "ManageIQ" as opposed to "Manageiq": https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397324661
- [ ] Change the boilerplate roles to something more restrictive: https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397319716
- [ ] Fully spelled out keys: https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397322227
- [ ] Certs available outside of the build: https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397344335
- [ ] Do we need productizable kind names based on APP_NAME ?  Not even sure that's possible.
- [ ] Some other minor formatting cleanup and variable naming

**Comment by carbonin** [comment]
Closing this as I opened individual issues for the remaining TODO items.
