### ISSUE TITLE
Operator P2 Issues

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-pods#599]
The following issues are designated as priority 2 for the Kasparov release
- [x] [Document how to rebuild images with non-redistributable VMware libs](https://github.com/ManageIQ/manageiq-pods/issues/538)
- [ ] [Things that do not work in pods](https://github.com/ManageIQ/manageiq-pods/issues/595)
- [ ] [Support aggregated logging](https://github.com/ManageIQ/manageiq/issues/19582)
- [ ] [Generate metrics for autoscaling](https://github.com/ManageIQ/manageiq-pods/issues/668) 
- [ ] [Autoscaling of worker pods](https://github.com/ManageIQ/manageiq-pods/issues/640)

**Comment by gtanzillo** [comment]
Closing this epic issue as we are tracking the individual issues separately on the roadmap.
